spring.application.name=authorization
server.address=127.0.0.1
server.port=9091
spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.security=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/polybank_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:polybank_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}

spring.security.oauth2.authorizationserver.issuerUrl=http://localhost:9091
spring.security.oauth2.authorizationserver.allowedOrigins[0]=http://localhost:5173
spring.security.oauth2.authorizationserver.allowedOrigins[1]=http://localhost:4173
spring.security.oauth2.authorizationserver.allowedOrigins[2]=http://localhost:3000
spring.security.oauth2.authorizationserver.allowedOrigins[3]=http://localhost:8080

spring.security.oauth2.authorizationserver.accessExpirationMinutes=${ACCESS_EXPIRATION_MINUTES:15}
spring.security.oauth2.authorizationserver.refreshExpirationMinutes=${REFRESH_TOKEN_EXPIRATION_MINUTES:60}
spring.security.oauth2.authorizationserver.frontendRedirectUri=http://localhost:5173/oauth/callback
spring.security.oauth2.authorizationserver.frontendRedirectLogout=http://localhost:5173/login
spring.security.oauth2.authorizationserver.swaggerRedirectUri=http://localhost:8080/swagger-ui/oauth2-redirect.html
spring.security.oauth2.authorizationserver.redis.ttl=120

spring.data.redis.database=${REDIS_DATABASE:0}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.username=${REDIS_USER:default}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.client-type=lettuce
spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.lettuce.pool.max-idle=8

spring.session.timeout=1800
spring.session.data.redis.flush-mode=on_save
spring.session.data.redis.namespace=authorization:session
spring.session.save-mode=on_set_attribute

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.tags.application=authorization
