spring.application.name=polybank
spring.mvc.apiversion.use.path-segment=0
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:polybank_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:polybank_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:polybank_password}}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always