spring.application.name=polybank
spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/polybank_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.cors.allowed-origin=http://localhost:5173
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
