spring.application.name=polybank
spring.mvc.apiversion.use.path-segment=0
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/polybank_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES}