spring.application.name=notification
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/polybank_notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:polybank_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml