spring.application.name=notification
spring.config.import=optional:file:.env[.properties]

server.forward-headers-strategy=framework

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/polybank_notification_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:polybank_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
spring.kafka.consumer.group-id=polybank-notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.metrics.tags.application=notification