apiVersion: v1
kind: Secret
metadata:
  name: polybank-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgresAuth.username | quote }}
  password: {{ .Values.postgresAuth.password | quote }}
  postgres-password: {{ .Values.postgresAuth.postgresPassword | quote }}
  database: {{ .Values.postgresAuth.database | quote }}

  POSTGRES_USER: {{ .Values.postgresAuth.username | quote }}
  POSTGRES_DB: {{ .Values.postgresAuth.database | quote }}

  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresAuth.database }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresAuth.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresAuth.password | quote }}