namespace: polybank
appName: polybank-backend
image:
  repository: 192.168.130.81:5000/polybank
  tag: latest
replicas: 2
appServicePort: 8080
metricsContainerPort: 5300
service:
  type: NodePort
  nodePort: 30090
resources:
  requests:
    memory: "384Mi"
    cpu: "300m"
  limits:
    memory: "768Mi"
    cpu: "750m"

startupProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

appVars:
  APP_JWT_EXPIRATION_MINUTES:
    secret: false
    value: "60"
  APP_CORS_ALLOWED_ORIGIN:
    secret: false
    value: "http://192.168.130.82:30091,http://192.168.130.83:30091,http://192.168.130.84:30091"
  APP_JWT_SECRET:
    secret: true
    value: ""

postgresAuth:
  username: polybank_user
  password: ""
  postgresPassword: ""
  database: polybank_db

externalPostgres:
  host: ""
  port: 5432

webapp:
  appName: polybank-webapp
  image:
    repository: 192.168.130.81:5000/polybank-webapp
    tag: latest
  replicas: 1
  containerPort: 80
  service:
    type: NodePort
    nodePort: 30091
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

cnpg:
  enabled: true
  instances: 3
  storageSize: 10Gi
  storageClass: "local-path"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

trafficGenerator:
  enabled: true
  appName: polybank-traffic-generator
  image:
    repository: 192.168.130.81:5000/polybank-traffic-generator
    tag: latest
  replicas: 1
  containerPort: 6060
  service:
    type: NodePort
    nodePort: 30093
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

notification:
  appName: polybank-notification
  image:
    repository: 192.168.130.81:5000/polybank-notification
    tag: latest
  replicas: 1
  appServicePort: 8080
  service:
    type: NodePort
    nodePort: 30092
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  startupProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  kafka:
    bootstrapServers: "192.168.130.82:9092"
  mail:
    host: "192.168.130.81"
    port: 1025
