namespace: polybank
appName: polybank-backend
image:
  repository: 192.168.130.81:5000/polybank
  tag: latest
replicas: 2
appServicePort: 8080
metricsContainerPort: 5300
service:
  type: NodePort
  nodePort: 30090
ingress:
  enabled: false
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 30

appVars:
  APP_JWT_EXPIRATION_MINUTES:
    secret: false
    value: "60"
  APP_CORS_ALLOWED_ORIGIN:
    secret: false
    value: "http://192.168.130.82:30091,http://192.168.130.83:30091,http://192.168.130.84:30091"
  APP_JWT_SECRET:
    secret: true
    value: ""

postgresAuth:
  username: polybank_user
  password: ""
  postgresPassword: ""
  database: polybank_db

externalPostgres:
  host: ""
  port: 5432

webapp:
  appName: polybank-webapp
  image:
    repository: 192.168.130.81:5000/polybank-webapp
    tag: latest
  replicas: 1
  containerPort: 80
  service:
    type: NodePort
    nodePort: 30091
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

postgresql:
  enabled: true
  architecture: replication
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: polybank_user
    database: polybank_db
    existingSecret: "polybank-backend-secret"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      usernameKey: username
      databaseKey: database
      replicationPasswordKey: replication-password
  primary:
    persistence:
      enabled: true
      existingClaim: "data-polybank-postgresql-0"
      size: 10Gi
      storageClass: "local-path"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    podAntiAffinityPreset: hard
  readReplicas:
    replicaCount: 1
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "local-path"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    podAntiAffinityPreset: hard
