namespace: polybank-test
appName: polybank-backend
replicas: 1
image:
  repository: 192.168.130.81:5000/polybank-test
  tag: latest
service:
  type: NodePort
  nodePort: 30190
resources:
  requests:
    memory: "192Mi"
    cpu: "75m"
  limits:
    memory: "768Mi"
    cpu: "750m"

startupProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 40

webapp:
  appName: polybank-webapp
  replicas: 1
  image:
    repository: 192.168.130.81:5000/polybank-webapp-test
    tag: latest
  service:
    type: NodePort
    nodePort: 30191
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"

appVars:
  APP_CORS_ALLOWED_ORIGIN:
    secret: false
    value: "http://192.168.130.82:30191,http://192.168.130.83:30191,http://192.168.130.84:30191"

cnpg:
  enabled: true
  instances: 2
  storageSize: 2Gi
  storageClass: "local-path"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

postgresAuth:
  username: polybank_test_user
  database: polybank_test_db
