apiVersion: v1
kind: Service
metadata:
  name: polybank-webapp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: polybank
    app.kubernetes.io/component: webapp
spec:
  type: {{ .Values.webapp.service.type }}
  selector:
    app: {{ .Values.webapp.appName }}
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.webapp.service.nodePort }}
