apiVersion: v1
kind: Service
metadata:
  name: polybank-traffic-generator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: polybank
    app.kubernetes.io/component: traffic-generator
spec:
  type: {{ .Values.trafficGenerator.service.type }}
  selector:
    app: {{ .Values.trafficGenerator.appName }}
  ports:
    - name: http
      port: {{ .Values.trafficGenerator.containerPort }}
      targetPort: http
      nodePort: {{ .Values.trafficGenerator.service.nodePort }}
