apiVersion: v1
kind: Secret
metadata:
  name: polybank-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  REDIS_USER: {{ .Values.redis.auth.user | quote }}
  REDIS_DATABASE: {{ .Values.redis.auth.database | quote }}
  REDIS_HOST: "polybank-redis"
  REDIS_PORT: {{ .Values.redis.containerPort | quote }}
  SPRING_DATA_REDIS_HOST: "polybank-redis"
  SPRING_DATA_REDIS_PORT: {{ .Values.redis.containerPort | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
