apiVersion: v1
kind: Service
metadata:
  name: polybank-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: polybank
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.redis.appName }}
  ports:
    - name: redis
      port: {{ .Values.redis.containerPort }}
      targetPort: redis
