apiVersion: v1
kind: Secret
metadata:
  name: polybank-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
  {{ $username := required "Set .Values.postgresAuth.username" .Values.postgresAuth.username }}
  {{ $password := required "Set .Values.postgresAuth.password" .Values.postgresAuth.password }}
  {{ $postgresPassword := required "Set .Values.postgresAuth.postgresPassword" .Values.postgresAuth.postgresPassword }}
  {{ $database := required "Set .Values.postgresAuth.database" .Values.postgresAuth.database }}
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  postgres-password: {{ $postgresPassword | quote }}
  database: {{ $database | quote }}

  POSTGRES_USER: {{ $username | quote }}
  POSTGRES_DB: {{ $database | quote }}

  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ $database }}"
  SPRING_DATASOURCE_USERNAME: {{ $username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ $password | quote }}

  {{ $jwtSecret := required "Set .Values.secretEnv.APP_JWT_SECRET" .Values.secretEnv.APP_JWT_SECRET }}
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}