apiVersion: v1
kind: Secret
metadata:
  name: polybank-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ $auth := .Values.global.postgresql.auth }}
{{ $username := required "Set .Values.global.postgresql.auth.username" $auth.username }}
{{ $password := required "Set .Values.global.postgresql.auth.password" $auth.password }}
{{ $postgresPassword := required "Set .Values.global.postgresql.auth.postgresPassword" $auth.postgresPassword }}
{{ $database := required "Set .Values.global.postgresql.auth.database" $auth.database }}
{{ $jwtSecret := required "Set .Values.jwt.secret" .Values.jwt.secret }}
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  postgres-password: {{ $postgresPassword | quote }}
  database: {{ $database | quote }}

  POSTGRES_USER: {{ $username | quote }}
  POSTGRES_DB: {{ $database | quote }}

  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ $database }}"
  SPRING_DATASOURCE_USERNAME: {{ $username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ $password | quote }}

  JWT_SECRET: {{ $jwtSecret | quote }}